ceg_article_create:
    path: /create/
    defaults: { _controller: CEGArticleBundle:Default:createArticle }

ceg_article_show:
    path: /show/{id}
    defaults: { _controller: CEGArticleBundle:Default:showArticle }

ceg_article_delete:
    path: /delete/{id}
    defaults: { _controller: CEGArticleBundle:Default:deleteArticle }

ceg_article_update:
    path: /update/{id}
    defaults: { _controller: CEGArticleBundle:Default:updateArticle }

ceg_article_check:
    path: /check/{id}/{check}
    defaults: { _controller: CEGArticleBundle:Default:checkArticle }

ceg_article_list:
    path: /list/{page}
    defaults: {_controller: CEGArticleBundle:Default:list }

ceg_image_delete:
    path: /deleteFile/{id}
    defaults: { _controller: CEGArticleBundle:Default:deleteImage }
