ceg_application_homepage:
    path:     /
    defaults: { _controller: CEGApplicationBundle:Default:index }

get_user:
    path:     /getUser
    defaults: { _controller: CEGApplicationBundle:User:getUser }

ceg_application_club:
    path: /club
    defaults: { _controller: CEGApplicationBundle:Default:club }

ceg_application_test:
    path: /test
    defaults: { _controller: CEGApplicationBundle:Default:testIndex }
